name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Run Checkmarx 
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@33a450f2a0ae798ec9546bef50903edacf41c1e7
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://eu.ast.checkmarx.net 
          # Provide the Tenant for AST portal URL
          cx_tenant: dp_wp_account
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          # Select a Checkmarx Project Name
          project_name: KB_JShop_GHA_SCS # optional, default is ${{ github.repository }}
          # Branch name
          branch: master
          # GitHub API Token
          github_token: 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 #${{ secrets.GH_TOKEN }}
          # Additional parameters for AST scan
          # additional_params:  --scan-types scs --scs-engines scorecard --scs-repo-url https://api.github.com/Kabacx/juice-shop --scs-repo-token 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 --debug
          additional_params:  --scan-types scs --scs-engines scorecard --debug --scs-repo-url https://github.com/Kabacx/juice-shop --scs-repo-token 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
     #END
      
