name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Run Checkmarx 
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@33a450f2a0ae798ec9546bef50903edacf41c1e7
        uses: Checkmarx/ast-github-action@2.0.4
        with:
          base_uri: https://eu.ast.checkmarx.net 
          # Provide the Tenant for AST portal URL
          cx_tenant: dp_wp_account
          # Client ID for AST portal authentication
          cx_client_id: KB_Github
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          # Select a Checkmarx Project Name
          project_name: KB_Juice_GitHub_Action # optional, default is ${{ github.repository }}
          # Branch name
          branch: main
          # GitHub API Token
          github_token: ${{ secrets.GH_TOKEN }}
          # Additional parameters for AST scan
          additional_params: '--scs-repo-url "https://github.com/Kabacx/Juice-shop" --scs-repo-token "ghp_Nf82HMkGBiGqjx3qBiCk2clBpzzYyz1KIU3u"' # optional, default is 
      #END
